name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.0
      - name: Build project
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.0
        with:
          cmd: ./gradlew cAT
          api: 21
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Final checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Lint-report
          path: sample/build/reports/lint-results.html
