name: pull request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build pull request
    runs-on: macOS-13
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/actions/wrapper-validation@v4
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.1.16.7
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        uses: actions/upload-artifact@v4
        with:
          name: Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Final checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        with:
          name: Lint-report
          path: sample/build/reports/lint-results*.html
